/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_quit_dialog (void);
GtkWidget* create_main_menu (void);
GtkWidget* create_error_dialog (void);
GtkWidget* create_stations_window (void);
