/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *image_scrolledwindow;
  GtkWidget *image_viewport;
  GtkWidget *alignment6;
  GtkWidget *wefax_drawingarea;
  GtkWidget *image_label;
  GtkWidget *hbox1;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *scope;
  GtkWidget *scope_label;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *spectrum;
  GtkWidget *label3;
  GtkWidget *frame4;
  GtkWidget *alignment4;
  GtkWidget *control_table;
  GtkWidget *start_icon;
  GtkWidget *sync_icon;
  GtkWidget *decode_icon;
  GtkWidget *save_icon;
  GtkWidget *hseparator1;
  GtkWidget *control_drawingarea;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *save_checkbutton;
  GtkWidget *label25;
  GtkWidget *start_togglebutton;
  GtkWidget *skip_button;
  GtkObject *deslant_spinbutton_adj;
  GtkWidget *deslant_spinbutton;
  GtkWidget *label4;
  GtkWidget *frame8;
  GtkWidget *alignment5;
  GtkWidget *text_scrolledwindow;
  GtkWidget *textview;
  GtkWidget *label18;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (main_window), 4);
  gtk_window_set_title (GTK_WINDOW (main_window), _("Xwefax"));
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);

  image_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (image_scrolledwindow);
  gtk_container_add (GTK_CONTAINER (frame1), image_scrolledwindow);
  gtk_container_set_border_width (GTK_CONTAINER (image_scrolledwindow), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (image_scrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  image_viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (image_viewport);
  gtk_container_add (GTK_CONTAINER (image_scrolledwindow), image_viewport);
  gtk_container_set_border_width (GTK_CONTAINER (image_viewport), 2);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (image_viewport), GTK_SHADOW_ETCHED_IN);

  alignment6 = gtk_alignment_new (0, 0, 1, 1);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (image_viewport), alignment6);

  wefax_drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (wefax_drawingarea);
  gtk_container_add (GTK_CONTAINER (alignment6), wefax_drawingarea);
  gtk_widget_set_events (wefax_drawingarea, GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK);

  image_label = gtk_label_new (_("Wefax Image"));
  gtk_widget_show (image_label);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), image_label);
  gtk_misc_set_padding (GTK_MISC (image_label), 2, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox1), frame2, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 2);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 4, 4, 4, 4);

  scope = gtk_drawing_area_new ();
  gtk_widget_show (scope);
  gtk_container_add (GTK_CONTAINER (alignment2), scope);
  gtk_widget_set_size_request (scope, 255, -1);

  scope_label = gtk_label_new (_("Signal"));
  gtk_widget_show (scope_label);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), scope_label);
  gtk_misc_set_padding (GTK_MISC (scope_label), 2, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox1), frame3, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 2);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 4, 4, 4, 4);

  spectrum = gtk_drawing_area_new ();
  gtk_widget_show (spectrum);
  gtk_container_add (GTK_CONTAINER (alignment3), spectrum);
  gtk_widget_set_size_request (spectrum, 255, -1);
  gtk_widget_set_events (spectrum, GDK_BUTTON_PRESS_MASK);

  label3 = gtk_label_new (_("Spectrum"));
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label3);
  gtk_misc_set_padding (GTK_MISC (label3), 2, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (hbox1), frame4, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 2);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame4), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 4, 4, 4, 4);

  control_table = gtk_table_new (7, 3, FALSE);
  gtk_widget_show (control_table);
  gtk_container_add (GTK_CONTAINER (alignment4), control_table);

  start_icon = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (start_icon);
  gtk_table_attach (GTK_TABLE (control_table), start_icon, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  sync_icon = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (sync_icon);
  gtk_table_attach (GTK_TABLE (control_table), sync_icon, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  decode_icon = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (decode_icon);
  gtk_table_attach (GTK_TABLE (control_table), decode_icon, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  save_icon = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (save_icon);
  gtk_table_attach (GTK_TABLE (control_table), save_icon, 1, 2, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (control_table), hseparator1, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 2);

  control_drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (control_drawingarea);
  gtk_table_attach (GTK_TABLE (control_table), control_drawingarea, 2, 3, 0, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 2, 0);
  gtk_widget_set_size_request (control_drawingarea, 24, -1);
  gtk_tooltips_set_tip (tooltips, control_drawingarea, _("Level gauge for signal, start tone or stop tone"), NULL);

  label22 = gtk_label_new (_("Start Tone"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (control_table), label22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new (_("Sync Pulse"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (control_table), label23, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new (_("Decoding"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (control_table), label24, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  save_checkbutton = gtk_check_button_new_with_mnemonic (_("Save Img"));
  gtk_widget_show (save_checkbutton);
  gtk_table_attach (GTK_TABLE (control_table), save_checkbutton, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, save_checkbutton, _("Enable Saving of Image"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (save_checkbutton), TRUE);

  label25 = gtk_label_new (_("Fix Slant "));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (control_table), label25, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  start_togglebutton = gtk_toggle_button_new ();
  gtk_widget_show (start_togglebutton);
  gtk_table_attach (GTK_TABLE (control_table), start_togglebutton, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_tooltips_set_tip (tooltips, start_togglebutton, _("Toggle Standby/Receive States"), NULL);

  skip_button = gtk_button_new_with_mnemonic (_("Skip"));
  gtk_widget_show (skip_button);
  gtk_table_attach (GTK_TABLE (control_table), skip_button, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, skip_button, _("Skip the Current Operation"), NULL);

  deslant_spinbutton_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 0);
  deslant_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (deslant_spinbutton_adj), 1, 0);
  gtk_widget_show (deslant_spinbutton);
  gtk_table_attach (GTK_TABLE (control_table), deslant_spinbutton, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, deslant_spinbutton, _("Correction in Pix/1000 of image slant"), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (deslant_spinbutton), TRUE);

  label4 = gtk_label_new (_("Xwefax Control"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label4);
  gtk_misc_set_padding (GTK_MISC (label4), 2, 0);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (hbox1), frame8, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 2);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame8), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 4, 4, 4, 4);

  text_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (text_scrolledwindow);
  gtk_container_add (GTK_CONTAINER (alignment5), text_scrolledwindow);
  gtk_container_set_border_width (GTK_CONTAINER (text_scrolledwindow), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (text_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (text_scrolledwindow), GTK_SHADOW_IN);

  textview = gtk_text_view_new ();
  gtk_widget_show (textview);
  gtk_container_add (GTK_CONTAINER (text_scrolledwindow), textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview), FALSE);

  label18 = gtk_label_new (_("Xwefax Messages"));
  gtk_widget_show (label18);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label18);
  gtk_misc_set_padding (GTK_MISC (label18), 2, 0);

  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (on_main_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy",
                    G_CALLBACK (on_main_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) wefax_drawingarea, "button_press_event",
                    G_CALLBACK (on_wefax_drawingarea_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) wefax_drawingarea, "expose_event",
                    G_CALLBACK (on_wefax_drawingarea_expose_event),
                    NULL);
  g_signal_connect ((gpointer) scope, "size_allocate",
                    G_CALLBACK (on_scope_size_allocate),
                    NULL);
  g_signal_connect ((gpointer) scope, "expose_event",
                    G_CALLBACK (on_scope_expose_event),
                    NULL);
  g_signal_connect ((gpointer) spectrum, "button_press_event",
                    G_CALLBACK (on_spectrum_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) spectrum, "size_allocate",
                    G_CALLBACK (on_spectrum_size_allocate),
                    NULL);
  g_signal_connect ((gpointer) spectrum, "expose_event",
                    G_CALLBACK (on_spectrum_expose_event),
                    NULL);
  g_signal_connect ((gpointer) control_drawingarea, "expose_event",
                    G_CALLBACK (on_control_drawingarea_expose_event),
                    NULL);
  g_signal_connect ((gpointer) save_checkbutton, "toggled",
                    G_CALLBACK (on_save_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) start_togglebutton, "toggled",
                    G_CALLBACK (on_start_togglebutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) skip_button, "clicked",
                    G_CALLBACK (on_skip_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) deslant_spinbutton, "value_changed",
                    G_CALLBACK (on_deslant_spinbutton_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (main_window, image_scrolledwindow, "image_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, image_viewport, "image_viewport");
  GLADE_HOOKUP_OBJECT (main_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (main_window, wefax_drawingarea, "wefax_drawingarea");
  GLADE_HOOKUP_OBJECT (main_window, image_label, "image_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (main_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main_window, scope, "scope");
  GLADE_HOOKUP_OBJECT (main_window, scope_label, "scope_label");
  GLADE_HOOKUP_OBJECT (main_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, spectrum, "spectrum");
  GLADE_HOOKUP_OBJECT (main_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (main_window, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (main_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main_window, control_table, "control_table");
  GLADE_HOOKUP_OBJECT (main_window, start_icon, "start_icon");
  GLADE_HOOKUP_OBJECT (main_window, sync_icon, "sync_icon");
  GLADE_HOOKUP_OBJECT (main_window, decode_icon, "decode_icon");
  GLADE_HOOKUP_OBJECT (main_window, save_icon, "save_icon");
  GLADE_HOOKUP_OBJECT (main_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (main_window, control_drawingarea, "control_drawingarea");
  GLADE_HOOKUP_OBJECT (main_window, label22, "label22");
  GLADE_HOOKUP_OBJECT (main_window, label23, "label23");
  GLADE_HOOKUP_OBJECT (main_window, label24, "label24");
  GLADE_HOOKUP_OBJECT (main_window, save_checkbutton, "save_checkbutton");
  GLADE_HOOKUP_OBJECT (main_window, label25, "label25");
  GLADE_HOOKUP_OBJECT (main_window, start_togglebutton, "start_togglebutton");
  GLADE_HOOKUP_OBJECT (main_window, skip_button, "skip_button");
  GLADE_HOOKUP_OBJECT (main_window, deslant_spinbutton, "deslant_spinbutton");
  GLADE_HOOKUP_OBJECT (main_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (main_window, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (main_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (main_window, text_scrolledwindow, "text_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, textview, "textview");
  GLADE_HOOKUP_OBJECT (main_window, label18, "label18");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  return main_window;
}

GtkWidget*
create_quit_dialog (void)
{
  GtkWidget *quit_dialog;
  GtkWidget *vbox7;
  GtkWidget *frame7;
  GtkWidget *hbox5;
  GtkWidget *image4;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *hbuttonbox1;
  GtkWidget *quit_cancel_button;
  GtkWidget *button2;

  quit_dialog = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (quit_dialog), 4);
  gtk_widget_set_events (quit_dialog, GDK_PROXIMITY_OUT_MASK);
  gtk_window_set_title (GTK_WINDOW (quit_dialog), _("Xwefax"));
  gtk_window_set_position (GTK_WINDOW (quit_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (quit_dialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (quit_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox7 = GTK_DIALOG (quit_dialog)->vbox;
  gtk_widget_show (vbox7);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox7), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 4);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (frame7), hbox5);

  image4 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox5), image4, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image4, 56, 56);

  label16 = gtk_label_new (_("Quit Xwefax?"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox5), label16, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label16), 4, 0);

  label17 = gtk_label_new (_("Quit?"));
  gtk_widget_show (label17);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label17);
  gtk_misc_set_padding (GTK_MISC (label17), 4, 0);

  hbuttonbox1 = GTK_DIALOG (quit_dialog)->action_area;
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  quit_cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (quit_cancel_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (quit_dialog), quit_cancel_button, GTK_RESPONSE_CANCEL);
  gtk_container_set_border_width (GTK_CONTAINER (quit_cancel_button), 2);
  GTK_WIDGET_SET_FLAGS (quit_cancel_button, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (quit_dialog), button2, GTK_RESPONSE_APPLY);
  gtk_container_set_border_width (GTK_CONTAINER (button2), 2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) quit_cancel_button, "clicked",
                    G_CALLBACK (on_quit_cancel_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_quit_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, quit_dialog, "quit_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (quit_dialog, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (quit_dialog, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (quit_dialog, image4, "image4");
  GLADE_HOOKUP_OBJECT (quit_dialog, label16, "label16");
  GLADE_HOOKUP_OBJECT (quit_dialog, label17, "label17");
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (quit_dialog, quit_cancel_button, "quit_cancel_button");
  GLADE_HOOKUP_OBJECT (quit_dialog, button2, "button2");

  return quit_dialog;
}

GtkWidget*
create_main_menu (void)
{
  GtkWidget *main_menu;
  GtkWidget *station_list;
  GtkWidget *separator3;
  GtkWidget *item2;
  GtkWidget *image215;
  GtkWidget *item2_menu;
  GSList *zerocrossing_group = NULL;
  GtkWidget *zerocrossing;
  GtkWidget *bilevel;
  GtkWidget *rpm;
  GtkWidget *image216;
  GtkWidget *rpm_menu;
  GSList *rpm60_group = NULL;
  GtkWidget *rpm60;
  GtkWidget *rpm90;
  GtkWidget *rpm100;
  GtkWidget *rpm120;
  GtkWidget *rpm180;
  GtkWidget *rpm240;
  GtkWidget *resolution;
  GtkWidget *image217;
  GtkWidget *resolution_menu;
  GSList *pix600_group = NULL;
  GtkWidget *pix600;
  GtkWidget *pix1200;
  GtkWidget *ioc_value;
  GtkWidget *image218;
  GtkWidget *ioc_value_menu;
  GSList *ioc288_group = NULL;
  GtkWidget *ioc288;
  GtkWidget *ioc576;
  GtkWidget *phasing_lines;
  GtkWidget *image219;
  GtkWidget *phasing_lines_menu;
  GSList *phl10_group = NULL;
  GtkWidget *phl10;
  GtkWidget *phl20;
  GtkWidget *phl40;
  GtkWidget *phl60;
  GtkWidget *in_image_phasing;
  GtkWidget *separator4;
  GtkWidget *enhance_image;
  GtkWidget *image220;
  GtkWidget *enhance_image_menu;
  GSList *ime0_group = NULL;
  GtkWidget *ime0;
  GtkWidget *ime1;
  GtkWidget *ime2;
  GtkWidget *item1;
  GtkWidget *image221;
  GtkWidget *item1_menu;
  GSList *jpeg_group = NULL;
  GtkWidget *jpeg;
  GtkWidget *pgm;
  GtkWidget *both;
  GtkWidget *separator2;
  GtkWidget *capture_setup;
  GtkWidget *separator5;
  GtkWidget *quit;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_menu = gtk_menu_new ();
  gtk_container_set_border_width (GTK_CONTAINER (main_menu), 2);

  station_list = gtk_menu_item_new_with_mnemonic (_("Station List"));
  gtk_widget_show (station_list);
  gtk_container_add (GTK_CONTAINER (main_menu), station_list);
  gtk_tooltips_set_tip (tooltips, station_list, _("Open Stations List Treeview"), NULL);

  separator3 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (main_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  item2 = gtk_image_menu_item_new_with_mnemonic (_("FM Decoder"));
  gtk_widget_show (item2);
  gtk_container_add (GTK_CONTAINER (main_menu), item2);
  gtk_tooltips_set_tip (tooltips, item2, _("Select WEFAX FM signal decoder"), NULL);

  image215 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image215);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item2), image215);

  item2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (item2), item2_menu);

  zerocrossing = gtk_radio_menu_item_new_with_mnemonic (zerocrossing_group, _("Zero Crossing"));
  zerocrossing_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (zerocrossing));
  gtk_widget_show (zerocrossing);
  gtk_container_add (GTK_CONTAINER (item2_menu), zerocrossing);
  gtk_tooltips_set_tip (tooltips, zerocrossing, _("Zero Crossing Detector"), NULL);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (zerocrossing), TRUE);

  bilevel = gtk_radio_menu_item_new_with_mnemonic (zerocrossing_group, _("Bilevel Detect"));
  zerocrossing_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bilevel));
  gtk_widget_show (bilevel);
  gtk_container_add (GTK_CONTAINER (item2_menu), bilevel);
  gtk_tooltips_set_tip (tooltips, bilevel, _("Bilevel Detector"), NULL);

  rpm = gtk_image_menu_item_new_with_mnemonic (_("RPM (lines/min)"));
  gtk_widget_show (rpm);
  gtk_container_add (GTK_CONTAINER (main_menu), rpm);
  gtk_tooltips_set_tip (tooltips, rpm, _("RPM or Line Transmission Rate (Lines/min)"), NULL);

  image216 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image216);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (rpm), image216);

  rpm_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (rpm), rpm_menu);

  rpm60 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("60"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm60));
  gtk_widget_show (rpm60);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm60);

  rpm90 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("90"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm90));
  gtk_widget_show (rpm90);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm90);

  rpm100 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("100"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm100));
  gtk_widget_show (rpm100);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm100);

  rpm120 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("120"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm120));
  gtk_widget_show (rpm120);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm120);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (rpm120), TRUE);

  rpm180 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("180"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm180));
  gtk_widget_show (rpm180);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm180);

  rpm240 = gtk_radio_menu_item_new_with_mnemonic (rpm60_group, _("240"));
  rpm60_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (rpm240));
  gtk_widget_show (rpm240);
  gtk_container_add (GTK_CONTAINER (rpm_menu), rpm240);

  resolution = gtk_image_menu_item_new_with_mnemonic (_("Resolution (pix/line)"));
  gtk_widget_show (resolution);
  gtk_container_add (GTK_CONTAINER (main_menu), resolution);
  gtk_tooltips_set_tip (tooltips, resolution, _("Horizontal Image Resolution (pixels/line)"), NULL);

  image217 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image217);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (resolution), image217);

  resolution_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (resolution), resolution_menu);

  pix600 = gtk_radio_menu_item_new_with_mnemonic (pix600_group, _("600"));
  pix600_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pix600));
  gtk_widget_show (pix600);
  gtk_container_add (GTK_CONTAINER (resolution_menu), pix600);

  pix1200 = gtk_radio_menu_item_new_with_mnemonic (pix600_group, _("1200"));
  pix600_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pix1200));
  gtk_widget_show (pix1200);
  gtk_container_add (GTK_CONTAINER (resolution_menu), pix1200);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (pix1200), TRUE);

  ioc_value = gtk_image_menu_item_new_with_mnemonic (_("IOC Value"));
  gtk_widget_show (ioc_value);
  gtk_container_add (GTK_CONTAINER (main_menu), ioc_value);
  gtk_tooltips_set_tip (tooltips, ioc_value, _("Index Of Co-Operation"), NULL);

  image218 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image218);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ioc_value), image218);

  ioc_value_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (ioc_value), ioc_value_menu);

  ioc288 = gtk_radio_menu_item_new_with_mnemonic (ioc288_group, _("288"));
  ioc288_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ioc288));
  gtk_widget_show (ioc288);
  gtk_container_add (GTK_CONTAINER (ioc_value_menu), ioc288);

  ioc576 = gtk_radio_menu_item_new_with_mnemonic (ioc288_group, _("576"));
  ioc288_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ioc576));
  gtk_widget_show (ioc576);
  gtk_container_add (GTK_CONTAINER (ioc_value_menu), ioc576);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ioc576), TRUE);

  phasing_lines = gtk_image_menu_item_new_with_mnemonic (_("Phasing Lines"));
  gtk_widget_show (phasing_lines);
  gtk_container_add (GTK_CONTAINER (main_menu), phasing_lines);
  gtk_tooltips_set_tip (tooltips, phasing_lines, _("Number of Lines with Phasing Pulses"), NULL);

  image219 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image219);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (phasing_lines), image219);

  phasing_lines_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (phasing_lines), phasing_lines_menu);

  phl10 = gtk_radio_menu_item_new_with_mnemonic (phl10_group, _("10"));
  phl10_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (phl10));
  gtk_widget_show (phl10);
  gtk_container_add (GTK_CONTAINER (phasing_lines_menu), phl10);

  phl20 = gtk_radio_menu_item_new_with_mnemonic (phl10_group, _("20"));
  phl10_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (phl20));
  gtk_widget_show (phl20);
  gtk_container_add (GTK_CONTAINER (phasing_lines_menu), phl20);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (phl20), TRUE);

  phl40 = gtk_radio_menu_item_new_with_mnemonic (phl10_group, _("40"));
  phl10_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (phl40));
  gtk_widget_show (phl40);
  gtk_container_add (GTK_CONTAINER (phasing_lines_menu), phl40);

  phl60 = gtk_radio_menu_item_new_with_mnemonic (phl10_group, _("60"));
  phl10_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (phl60));
  gtk_widget_show (phl60);
  gtk_container_add (GTK_CONTAINER (phasing_lines_menu), phl60);

  in_image_phasing = gtk_check_menu_item_new_with_mnemonic (_("In-Image Phasing"));
  gtk_widget_show (in_image_phasing);
  gtk_container_add (GTK_CONTAINER (main_menu), in_image_phasing);
  gtk_tooltips_set_tip (tooltips, in_image_phasing, _("Enable Detection of Phasing Pulses in the Image"), NULL);

  separator4 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (main_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  enhance_image = gtk_image_menu_item_new_with_mnemonic (_("Image Enhancement"));
  gtk_widget_show (enhance_image);
  gtk_container_add (GTK_CONTAINER (main_menu), enhance_image);
  gtk_tooltips_set_tip (tooltips, enhance_image, _("Image Enhancement"), NULL);

  image220 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image220);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (enhance_image), image220);

  enhance_image_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (enhance_image), enhance_image_menu);

  ime0 = gtk_radio_menu_item_new_with_mnemonic (ime0_group, _("None"));
  ime0_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ime0));
  gtk_widget_show (ime0);
  gtk_container_add (GTK_CONTAINER (enhance_image_menu), ime0);
  gtk_tooltips_set_tip (tooltips, ime0, _("Disable Image Enhancement"), NULL);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ime0), TRUE);

  ime1 = gtk_radio_menu_item_new_with_mnemonic (ime0_group, _("Normalize Contrast"));
  ime0_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ime1));
  gtk_widget_show (ime1);
  gtk_container_add (GTK_CONTAINER (enhance_image_menu), ime1);
  gtk_tooltips_set_tip (tooltips, ime1, _("Normalize Image by Stretching Contrast"), NULL);

  ime2 = gtk_radio_menu_item_new_with_mnemonic (ime0_group, _("Bilevel Image"));
  ime0_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ime2));
  gtk_widget_show (ime2);
  gtk_container_add (GTK_CONTAINER (enhance_image_menu), ime2);
  gtk_tooltips_set_tip (tooltips, ime2, _("Limit Pixel Values to White or Black"), NULL);

  item1 = gtk_image_menu_item_new_with_mnemonic (_("Image File Format"));
  gtk_widget_show (item1);
  gtk_container_add (GTK_CONTAINER (main_menu), item1);
  gtk_tooltips_set_tip (tooltips, item1, _("Select WEFAX Image File format for saving"), NULL);

  image221 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image221);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item1), image221);

  item1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (item1), item1_menu);

  jpeg = gtk_radio_menu_item_new_with_mnemonic (jpeg_group, _("JPEG"));
  jpeg_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (jpeg));
  gtk_widget_show (jpeg);
  gtk_container_add (GTK_CONTAINER (item1_menu), jpeg);
  gtk_tooltips_set_tip (tooltips, jpeg, _("Save Image in JPEG format"), NULL);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (jpeg), TRUE);

  pgm = gtk_radio_menu_item_new_with_mnemonic (jpeg_group, _("PGM"));
  jpeg_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pgm));
  gtk_widget_show (pgm);
  gtk_container_add (GTK_CONTAINER (item1_menu), pgm);
  gtk_tooltips_set_tip (tooltips, pgm, _("Save Image in PGM format"), NULL);

  both = gtk_radio_menu_item_new_with_mnemonic (jpeg_group, _("Both"));
  jpeg_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (both));
  gtk_widget_show (both);
  gtk_container_add (GTK_CONTAINER (item1_menu), both);
  gtk_tooltips_set_tip (tooltips, both, _("Save Image ig JPG and PGM format"), NULL);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (main_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  capture_setup = gtk_check_menu_item_new_with_mnemonic (_("Capture Setup"));
  gtk_widget_show (capture_setup);
  gtk_container_add (GTK_CONTAINER (main_menu), capture_setup);
  gtk_tooltips_set_tip (tooltips, capture_setup, _("Show Signal Strength in Scope and Gauge"), NULL);

  separator5 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (main_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (main_menu), quit);

  g_signal_connect ((gpointer) station_list, "activate",
                    G_CALLBACK (on_station_list_activate),
                    NULL);
  g_signal_connect ((gpointer) zerocrossing, "activate",
                    G_CALLBACK (on_zerocrossing_activate),
                    NULL);
  g_signal_connect ((gpointer) bilevel, "activate",
                    G_CALLBACK (on_bilevel_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm60, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm90, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm100, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm120, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm180, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) rpm240, "activate",
                    G_CALLBACK (on_rpm_activate),
                    NULL);
  g_signal_connect ((gpointer) pix600, "activate",
                    G_CALLBACK (on_pix_activate),
                    NULL);
  g_signal_connect ((gpointer) pix1200, "activate",
                    G_CALLBACK (on_pix_activate),
                    NULL);
  g_signal_connect ((gpointer) ioc288, "activate",
                    G_CALLBACK (on_ioc_activate),
                    NULL);
  g_signal_connect ((gpointer) ioc576, "activate",
                    G_CALLBACK (on_ioc_activate),
                    NULL);
  g_signal_connect ((gpointer) phl10, "activate",
                    G_CALLBACK (on_phl_activate),
                    NULL);
  g_signal_connect ((gpointer) phl20, "activate",
                    G_CALLBACK (on_phl_activate),
                    NULL);
  g_signal_connect ((gpointer) phl40, "activate",
                    G_CALLBACK (on_phl_activate),
                    NULL);
  g_signal_connect ((gpointer) phl60, "activate",
                    G_CALLBACK (on_phl_activate),
                    NULL);
  g_signal_connect ((gpointer) in_image_phasing, "activate",
                    G_CALLBACK (on_in_image_phasing_activate),
                    NULL);
  g_signal_connect ((gpointer) ime0, "activate",
                    G_CALLBACK (on_enhance_activate),
                    NULL);
  g_signal_connect ((gpointer) ime1, "activate",
                    G_CALLBACK (on_enhance_activate),
                    NULL);
  g_signal_connect ((gpointer) ime2, "activate",
                    G_CALLBACK (on_enhance_activate),
                    NULL);
  g_signal_connect ((gpointer) jpeg, "activate",
                    G_CALLBACK (on_jpeg_activate),
                    NULL);
  g_signal_connect ((gpointer) pgm, "activate",
                    G_CALLBACK (on_pgm_activate),
                    NULL);
  g_signal_connect ((gpointer) both, "activate",
                    G_CALLBACK (on_both_activate),
                    NULL);
  g_signal_connect ((gpointer) capture_setup, "activate",
                    G_CALLBACK (on_capture_setup_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_menu, main_menu, "main_menu");
  GLADE_HOOKUP_OBJECT (main_menu, station_list, "station_list");
  GLADE_HOOKUP_OBJECT (main_menu, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (main_menu, item2, "item2");
  GLADE_HOOKUP_OBJECT (main_menu, image215, "image215");
  GLADE_HOOKUP_OBJECT (main_menu, item2_menu, "item2_menu");
  GLADE_HOOKUP_OBJECT (main_menu, zerocrossing, "zerocrossing");
  GLADE_HOOKUP_OBJECT (main_menu, bilevel, "bilevel");
  GLADE_HOOKUP_OBJECT (main_menu, rpm, "rpm");
  GLADE_HOOKUP_OBJECT (main_menu, image216, "image216");
  GLADE_HOOKUP_OBJECT (main_menu, rpm_menu, "rpm_menu");
  GLADE_HOOKUP_OBJECT (main_menu, rpm60, "rpm60");
  GLADE_HOOKUP_OBJECT (main_menu, rpm90, "rpm90");
  GLADE_HOOKUP_OBJECT (main_menu, rpm100, "rpm100");
  GLADE_HOOKUP_OBJECT (main_menu, rpm120, "rpm120");
  GLADE_HOOKUP_OBJECT (main_menu, rpm180, "rpm180");
  GLADE_HOOKUP_OBJECT (main_menu, rpm240, "rpm240");
  GLADE_HOOKUP_OBJECT (main_menu, resolution, "resolution");
  GLADE_HOOKUP_OBJECT (main_menu, image217, "image217");
  GLADE_HOOKUP_OBJECT (main_menu, resolution_menu, "resolution_menu");
  GLADE_HOOKUP_OBJECT (main_menu, pix600, "pix600");
  GLADE_HOOKUP_OBJECT (main_menu, pix1200, "pix1200");
  GLADE_HOOKUP_OBJECT (main_menu, ioc_value, "ioc_value");
  GLADE_HOOKUP_OBJECT (main_menu, image218, "image218");
  GLADE_HOOKUP_OBJECT (main_menu, ioc_value_menu, "ioc_value_menu");
  GLADE_HOOKUP_OBJECT (main_menu, ioc288, "ioc288");
  GLADE_HOOKUP_OBJECT (main_menu, ioc576, "ioc576");
  GLADE_HOOKUP_OBJECT (main_menu, phasing_lines, "phasing_lines");
  GLADE_HOOKUP_OBJECT (main_menu, image219, "image219");
  GLADE_HOOKUP_OBJECT (main_menu, phasing_lines_menu, "phasing_lines_menu");
  GLADE_HOOKUP_OBJECT (main_menu, phl10, "phl10");
  GLADE_HOOKUP_OBJECT (main_menu, phl20, "phl20");
  GLADE_HOOKUP_OBJECT (main_menu, phl40, "phl40");
  GLADE_HOOKUP_OBJECT (main_menu, phl60, "phl60");
  GLADE_HOOKUP_OBJECT (main_menu, in_image_phasing, "in_image_phasing");
  GLADE_HOOKUP_OBJECT (main_menu, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (main_menu, enhance_image, "enhance_image");
  GLADE_HOOKUP_OBJECT (main_menu, image220, "image220");
  GLADE_HOOKUP_OBJECT (main_menu, enhance_image_menu, "enhance_image_menu");
  GLADE_HOOKUP_OBJECT (main_menu, ime0, "ime0");
  GLADE_HOOKUP_OBJECT (main_menu, ime1, "ime1");
  GLADE_HOOKUP_OBJECT (main_menu, ime2, "ime2");
  GLADE_HOOKUP_OBJECT (main_menu, item1, "item1");
  GLADE_HOOKUP_OBJECT (main_menu, image221, "image221");
  GLADE_HOOKUP_OBJECT (main_menu, item1_menu, "item1_menu");
  GLADE_HOOKUP_OBJECT (main_menu, jpeg, "jpeg");
  GLADE_HOOKUP_OBJECT (main_menu, pgm, "pgm");
  GLADE_HOOKUP_OBJECT (main_menu, both, "both");
  GLADE_HOOKUP_OBJECT (main_menu, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (main_menu, capture_setup, "capture_setup");
  GLADE_HOOKUP_OBJECT (main_menu, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (main_menu, quit, "quit");
  GLADE_HOOKUP_OBJECT_NO_REF (main_menu, tooltips, "tooltips");

  gtk_menu_set_accel_group (GTK_MENU (main_menu), accel_group);

  return main_menu;
}

GtkWidget*
create_error_dialog (void)
{
  GtkWidget *error_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame7;
  GtkWidget *hbox4;
  GtkWidget *image1;
  GtkWidget *error_message;
  GtkWidget *label21;
  GtkWidget *dialog_action_area1;
  GtkWidget *error_quit_button;
  GtkWidget *error_ok_button;

  error_dialog = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (error_dialog), 4);
  gtk_window_set_title (GTK_WINDOW (error_dialog), _("Xwefax"));
  gtk_window_set_position (GTK_WINDOW (error_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (error_dialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (error_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (error_dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 4);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame7), hbox4);

  image1 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox4), image1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image1, 56, 56);

  error_message = gtk_label_new (_("Generic Error Mesasge pop-up"));
  gtk_widget_show (error_message);
  gtk_box_pack_start (GTK_BOX (hbox4), error_message, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (error_message), 4, 0);

  label21 = gtk_label_new (_("Error"));
  gtk_widget_show (label21);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label21);
  gtk_misc_set_padding (GTK_MISC (label21), 4, 0);

  dialog_action_area1 = GTK_DIALOG (error_dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  error_quit_button = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (error_quit_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (error_dialog), error_quit_button, 0);
  gtk_container_set_border_width (GTK_CONTAINER (error_quit_button), 2);
  GTK_WIDGET_SET_FLAGS (error_quit_button, GTK_CAN_DEFAULT);

  error_ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (error_ok_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (error_dialog), error_ok_button, GTK_RESPONSE_OK);
  gtk_container_set_border_width (GTK_CONTAINER (error_ok_button), 2);
  GTK_WIDGET_SET_FLAGS (error_ok_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) error_dialog, "destroy",
                    G_CALLBACK (on_error_dialog_destroy),
                    NULL);
  g_signal_connect ((gpointer) error_dialog, "delete_event",
                    G_CALLBACK (on_error_dialog_delete_event),
                    NULL);
  g_signal_connect ((gpointer) error_quit_button, "clicked",
                    G_CALLBACK (on_error_quit_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) error_ok_button, "clicked",
                    G_CALLBACK (on_error_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, error_dialog, "error_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (error_dialog, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (error_dialog, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (error_dialog, image1, "image1");
  GLADE_HOOKUP_OBJECT (error_dialog, error_message, "error_message");
  GLADE_HOOKUP_OBJECT (error_dialog, label21, "label21");
  GLADE_HOOKUP_OBJECT_NO_REF (error_dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (error_dialog, error_quit_button, "error_quit_button");
  GLADE_HOOKUP_OBJECT (error_dialog, error_ok_button, "error_ok_button");

  return error_dialog;
}

GtkWidget*
create_stations_window (void)
{
  GtkWidget *stations_window;
  GtkWidget *vbox8;
  GtkWidget *scrolledwindow1;
  GtkWidget *stations_treeview;
  GtkWidget *hbox6;
  GtkWidget *down_button;
  GtkWidget *up_button;
  GtkWidget *delete_button;
  GtkWidget *new_button;
  GtkWidget *save_button;

  stations_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (stations_window), 4);
  gtk_window_set_title (GTK_WINDOW (stations_window), _("Stations Listing"));
  gtk_window_set_position (GTK_WINDOW (stations_window), GTK_WIN_POS_MOUSE);

  vbox8 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (stations_window), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow1, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  stations_treeview = gtk_tree_view_new ();
  gtk_widget_show (stations_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), stations_treeview);
  gtk_widget_set_size_request (stations_treeview, -1, 600);
  gtk_container_set_border_width (GTK_CONTAINER (stations_treeview), 2);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (stations_treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (stations_treeview), TRUE);

  hbox6 = gtk_hbox_new (TRUE, 4);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox6, FALSE, TRUE, 0);

  down_button = gtk_button_new_from_stock ("gtk-go-down");
  gtk_widget_show (down_button);
  gtk_box_pack_start (GTK_BOX (hbox6), down_button, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (down_button), 2);
  gtk_button_set_focus_on_click (GTK_BUTTON (down_button), FALSE);

  up_button = gtk_button_new_from_stock ("gtk-go-up");
  gtk_widget_show (up_button);
  gtk_box_pack_start (GTK_BOX (hbox6), up_button, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (up_button), 2);
  gtk_button_set_focus_on_click (GTK_BUTTON (up_button), FALSE);

  delete_button = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (delete_button);
  gtk_box_pack_start (GTK_BOX (hbox6), delete_button, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (delete_button), 2);

  new_button = gtk_button_new_from_stock ("gtk-new");
  gtk_widget_show (new_button);
  gtk_box_pack_start (GTK_BOX (hbox6), new_button, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (new_button), 2);

  save_button = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (save_button);
  gtk_box_pack_start (GTK_BOX (hbox6), save_button, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (save_button), 2);
  gtk_button_set_focus_on_click (GTK_BUTTON (save_button), FALSE);

  g_signal_connect ((gpointer) stations_window, "destroy",
                    G_CALLBACK (on_stations_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) stations_treeview, "cursor_changed",
                    G_CALLBACK (on_stations_treeview_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) stations_treeview, "button_press_event",
                    G_CALLBACK (on_stations_treeview_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) down_button, "clicked",
                    G_CALLBACK (on_down_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) up_button, "clicked",
                    G_CALLBACK (on_up_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete_button, "clicked",
                    G_CALLBACK (on_delete_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) new_button, "clicked",
                    G_CALLBACK (on_new_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_button, "clicked",
                    G_CALLBACK (on_save_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (stations_window, stations_window, "stations_window");
  GLADE_HOOKUP_OBJECT (stations_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (stations_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (stations_window, stations_treeview, "stations_treeview");
  GLADE_HOOKUP_OBJECT (stations_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (stations_window, down_button, "down_button");
  GLADE_HOOKUP_OBJECT (stations_window, up_button, "up_button");
  GLADE_HOOKUP_OBJECT (stations_window, delete_button, "delete_button");
  GLADE_HOOKUP_OBJECT (stations_window, new_button, "new_button");
  GLADE_HOOKUP_OBJECT (stations_window, save_button, "save_button");

  return stations_window;
}

