/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include "main.h"

/* Signal handler */
static void sig_handler( int signal );

/*------------------------------------------------------------------------*/

int
main (int argc, char *argv[])
{
  /* Command line option returned by getopt() */
  int option;

  /* New and old actions for sigaction() */
  struct sigaction sa_new, sa_old;


  /* Initialize new actions */
  sa_new.sa_handler = sig_handler;
  sigemptyset( &sa_new.sa_mask );
  sa_new.sa_flags = 0;

  /* Register function to handle signals */
  sigaction( SIGINT,  &sa_new, &sa_old );
  sigaction( SIGSEGV, &sa_new, 0 );
  sigaction( SIGFPE,  &sa_new, 0 );
  sigaction( SIGTERM, &sa_new, 0 );
  sigaction( SIGABRT, &sa_new, 0 );

  /* Process command line options */
  while( (option = getopt(argc, argv, "hv") ) != -1 )
	switch( option )
	{
	  case 'h' : /* Print usage and exit */
		Usage();
		return(0);

	  case 'v' : /* Print version */
		puts( PACKAGE_STRING );
		return(0);

	  default: /* Print usage and exit */
		Usage();
		exit(-1);

	} /* End of switch( option ) */

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_window = create_main_window ();
  gtk_window_set_title( GTK_WINDOW(main_window), PACKAGE_STRING );
  gtk_widget_show (main_window);

  /* Get scope widgets */
  gbl_scope    = lookup_widget( main_window, "scope" );
  gbl_spectrum = lookup_widget( main_window, "spectrum" );

  /* Create the text view scroller */
  gbl_text_scroller = lookup_widget( main_window, "text_scrolledwindow" );

  /* Get text buffer */
  gbl_text_buffer = gtk_text_view_get_buffer
	( GTK_TEXT_VIEW(lookup_widget(main_window, "textview")) );

  /* Create the popup menu to set it up */
  gbl_popup_menu = create_main_menu();

  /* Create some rendering tags */
  gtk_text_buffer_create_tag( gbl_text_buffer, "black",
	  "foreground", "black", NULL);
  gtk_text_buffer_create_tag( gbl_text_buffer, "red",
	  "foreground", "red", NULL);
  gtk_text_buffer_create_tag( gbl_text_buffer, "orange",
	  "foreground", "orange", NULL);
  gtk_text_buffer_create_tag( gbl_text_buffer, "green",
	  "foreground", "darkgreen", NULL);
  gtk_text_buffer_create_tag( gbl_text_buffer, "bold",
	  "weight", PANGO_WEIGHT_BOLD, NULL);

  /* Make a label for the start button */
  GtkWidget *button = lookup_widget( main_window, "start_togglebutton" );
  GtkWidget *rcve_status = gtk_label_new (_(" STANDBY "));
  gtk_label_set_width_chars( GTK_LABEL(rcve_status), 9 );
  gtk_widget_show (rcve_status);
  gtk_container_add (GTK_CONTAINER(button), rcve_status);
  gtk_label_set_justify (GTK_LABEL(rcve_status), GTK_JUSTIFY_LEFT);
  g_object_set_data_full (G_OBJECT(main_window), "rcve_status",
	  gtk_widget_ref (rcve_status), (GDestroyNotify) gtk_widget_unref);

  /* Clear image file name */
  gbl_image_file[0] = '\0';
  rc_data.sync_slant = 0.0;

  /* Print greeting message */
  char ver[24];
  snprintf( ver, sizeof(ver), _("Welcome to %s"), PACKAGE_STRING );
  Show_Message( ver, "bold" );
  SetFlag( RECEIVE_STOP );
  SetFlag( DISPLAY_SIGNAL );
  SetFlag( SAVE_IMAGE_JPG );
  SetFlag( SAVE_IMAGE );
  Set_Indicators( ICON_SAVE_YES );

  /* Load runtime config file, abort on error */
  gtk_idle_add( Load_Config, NULL );

  gtk_main ();

  return 0;
} /* main() */

/*------------------------------------------------------------------------*/

/*  sig_handler()
 *
 *  Signal Action Handler function
 */

static void sig_handler( int signal )
{
  Cleanup();

  fprintf( stderr, "\n" );
  switch( signal )
  {
	case SIGINT :
	  fprintf( stderr, "%s\n", _("xwefax: Exiting via User Interrupt") );
	  exit(-1);

	case SIGSEGV :
	  fprintf( stderr, "%s\n", _("xwefax: Segmentation Fault") );
	  exit(-1);

	case SIGFPE :
	  fprintf( stderr, "%s\n", _("xwefax: Floating Point Exception") );
	  exit(-1);

	case SIGABRT :
	  fprintf( stderr, "%s\n", _("xwefax: Abort Signal received") );
	  exit(-1);

	case SIGTERM :
	  fprintf( stderr, "%s\n", _("xwefax: Termination Request received") );
	  exit(-1);
  }

} /* End of sig_handler() */

/*------------------------------------------------------------------------*/

